# Generated by Django 5.2.7 on 2025-12-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='updated_at',
        ),
    ]
