# Generated by Django 5.2.7 on 2025-12-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_game', '0003_deck_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='description',
        ),
    ]
