# Generated by Django 5.2.3 on 2025-12-13 03:30

import bunker_game.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_game', '0004_remove_deck_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=bunker_game.models.generate_code, max_length=6, unique=True, verbose_name='Код комнаты')),
                ('max_players', models.PositiveIntegerField(default=10, verbose_name='Максимальное количество игроков')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('active', 'Игра началась'), ('finished', 'Игра завершена')], default='waiting', max_length=20, verbose_name='Статус комнаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала игры')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bunker_game.deck', verbose_name='Колода')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_rooms', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_players', to='bunker_game.room')),
            ],
            options={
                'verbose_name': 'Игрок в комнате',
                'verbose_name_plural': 'Игроки в комнатах',
                'unique_together': {('room', 'player')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='current_players',
            field=models.ManyToManyField(related_name='joined_rooms', through='bunker_game.RoomPlayer', to=settings.AUTH_USER_MODEL, verbose_name='Текущие игроки'),
        ),
    ]
