# Generated by Django 5.2.3 on 2025-12-25 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_game', '0005_room_roomplayer_room_current_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('catastrophe', 'Катастрофа'), ('bunker', 'Бункер'), ('profession', 'Профессия'), ('health', 'Здоровье'), ('hobby', 'Хобби'), ('personality', 'Характер'), ('luggage', 'Багаж'), ('additional', 'Дополнительный факт')], max_length=50, verbose_name='Тип карточки'),
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('current_phase', models.CharField(default='game', max_length=20)),
                ('current_player_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bunker_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bunker_games', to='bunker_game.card')),
                ('catastrophe_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catastrophe_games', to='bunker_game.card')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='bunker_game.room')),
            ],
            options={
                'verbose_name': 'Состояние игры',
                'verbose_name_plural': 'Состояния игр',
            },
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunker_game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_cards', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_cards', to='bunker_game.room')),
            ],
            options={
                'verbose_name': 'Карта игрока',
                'verbose_name_plural': 'Карты игроков',
                'unique_together': {('player', 'room', 'card')},
            },
        ),
    ]
